export const SOCKET_ACTIONS = {
    CONNECT_SOCKET: 'CONNECT_SOCKET',
    DISCONNECT_SOCKET: 'DISCONNECT_SOCKET',
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    PREVIOUS_REQUEST: 'PREVIOUS_REQUEST',
    LOADING: "LOADING",
    SET_REQUEST_DATA: "REQUEST_DATA"
}